version: '2.1'

orbs: 
  codecov: codecov/codecov@3.2.2
  node: circleci/node@4.7.0
workflows:
  upload-to-codecov:
    jobs: 
        - node/test: 
            post-steps: 
              - codecov/upload:
                token: CODECOV_TOKEN=7e480bf1-bb7a-45c1-a129-697c43312a1f


                
