version: '2.1'

orbs: 
  codecov: codecov/codecov@3.2.2
  node: circleci/node@4.7.0
workflows:
  upload-to-codecov:
    jobs: 
        - node/test: 
            post-steps: 
              - codecov/upload:
                token: CODECOV_TOKEN=bc2e56b0-7dfa-4d51-b660-a5ad1525deca
                